language: rust
cache: cargo
dist: xenial
rust: stable

jobs:
  include:
    - stage: test
      script:
        - bash scripts/clean-test.sh
    - stage: deploy-cargo
      script:
        - cargo publish --dry-run
        - cargo publish --token "$CARGO_TOKEN"
      if: tag IS present